import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.must.Matchers

class ReportsSpec extends AnyFlatSpec with Matchers:
  import Reports.replaceCat
  import Extensions.red

  "Strings with known value" should "be recognized and replaced" in {
    replaceCat("ASPH-G") must be("Asphalt")
    replaceCat("GRVL") must be("Gravel")
    replaceCat("TURF") must be("Grass")
    replaceCat("GRASS") must be("Grass")
    replaceCat("GRAVEL") must be("Gravel")
    replaceCat("ASPH") must be("Asphalt")
    replaceCat("TURF-G") must be("Grass")
    replaceCat("TURF-F") must be("Grass")
    replaceCat("MATS") must be("Mats")
    replaceCat("CONC") must be("Concrete")
    replaceCat("TURF-P") must be("Grass")
    replaceCat("CONC-G") must be("Concrete")
    replaceCat("GRAVEL-F") must be("Gravel")
    replaceCat("ASPH-TRTD") must be("Asphalt")
    replaceCat("TURF-GRVL") must be("Gravel")
    replaceCat("WATER") must be("Water")
    replaceCat("ASPH-TURF") must be("Asphalt")
    replaceCat("DIRT") must be("Dirt")
    replaceCat("GRVL-DIRT") must be("Gravel")
    replaceCat("DIRT-P") must be("Dirt")
    replaceCat("DIRT-TURF-G") must be("Dirt")
    replaceCat("CONC-TURF") must be("Concrete")
    replaceCat("DIRT-G") must be("Dirt")
    replaceCat("TURF-DIRT") must be("Grass")
    replaceCat("DIRT-F") must be("Dirt")
    replaceCat("GRVL-G") must be("Gravel")
    replaceCat("ASPH-CONC-G") must be("Asphalt")
    replaceCat("ASPH-P") must be("Asphalt")
    replaceCat("WATER-E") must be("Water")
    replaceCat("CONC-E") must be("Concrete")
    replaceCat("TURF-GRVL-F") must be("Gravel")
    replaceCat("ROOF-TOP") must be("Rooftop")
    replaceCat("ASPH-F") must be("Asphalt")
    replaceCat("ASPH-E") must be("Asphalt")
    replaceCat("GRVL-F") must be("Gravel")
    replaceCat("ASPH-DIRT") must be("Asphalt")
    replaceCat("ASPH-TRTD-P") must be("Asphalt")
    replaceCat("asphalt") must be("Asphalt")
    replaceCat("TREATED") must be("Treated")
    replaceCat("SAND") must be("Sand")
    replaceCat("GRVL-TRTD-P") must be("Gravel")
    replaceCat("TURF-DIRT-F") must be("Grass")
    replaceCat("TURF-GRVL-P") must be("Gravel")
    replaceCat("SOD") must be("Grass")
    replaceCat("TURF-E") must be("Grass")
    replaceCat("WOOD") must be("Wood")
    replaceCat("ALUM") must be("Aluminium")
    replaceCat("ASPH-TURF-P") must be("Asphalt")
    replaceCat("GRVL-DIRT-P") must be("Gravel")
    replaceCat("TRTD-DIRT") must be("Dirt")
    replaceCat("ASPH-CONC") must be("Asphalt")
    replaceCat("GRVL-P") must be("Gravel")
    replaceCat("GRAVEL-P") must be("Gravel")
    replaceCat("TURF-DIRT-P") must be("Grass")
    replaceCat("GRVL-TRTD-F") must be("Gravel")
    replaceCat("ASPH-GRVL-P") must be("Asphalt")
    replaceCat("ASPH-GRVL") must be("Asphalt")
    replaceCat("WATER-G") must be("Water")
    replaceCat("CONC-F") must be("Concrete")
    replaceCat("GRASS / SOD") must be("Grass")
    replaceCat("TURF-GRVL-G") must be("Gravel")
    replaceCat("DIRT-TURF") must be("Dirt")
    replaceCat("ASP") must be("Asphalt")
    replaceCat("GRAVEL-G") must be("Gravel")
    replaceCat("GRVL-TRTD") must be("Gravel")
    replaceCat("TRTD") must be("Treated")
    replaceCat("ASPH-TURF-F") must be("Asphalt")
    replaceCat("BRICK") must be("Brick")
    replaceCat("ROOFTOP") must be("Rooftop")
    replaceCat("DIRT-TRTD") must be("Dirt")
    replaceCat("DECK") must be("Deck")
    replaceCat("GRE") must be("Graded soil")
    replaceCat("CONC-P") must be("Concrete")
    replaceCat("CONC-GRVL") must be("Gravel")
    replaceCat("MATS-G") must be("Mats")
    replaceCat("ASPH-L") must be("Asphalt")
    replaceCat("TURF-DIRT-G") must be("Grass")
    replaceCat("ASPH-TURF-G") must be("Asphalt")
    replaceCat("DIRT-GRVL") must be("Gravel")
    replaceCat("GRAVEL-E") must be("Gravel")
    replaceCat("DIRT-GRVL-F") must be("Gravel")
    replaceCat("TURF-SAND-F") must be("Grass")
    replaceCat("GRVL-E") must be("Gravel")
    replaceCat("GRVL-TURF-F") must be("Gravel")
    replaceCat("GRVL-TURF") must be("Gravel")
    replaceCat("CALICHE") must be("Caliche")
    replaceCat("GRASS-F") must be("Grass")
    replaceCat("GRVL-DIRT-F") must be("Gravel")
    replaceCat("ASPH-DIRT-G") must be("Asphalt")
    replaceCat("ALUM-DECK") must be("Aluminium")
    replaceCat("TREATED-F") must be("Treated")
    replaceCat("OIL&CHIP-T-G") must be("Oil")
    replaceCat("CONC-GRVL-G") must be("Gravel")
    replaceCat("ASPH-GRVL-F") must be("Asphalt")
    replaceCat("CON") must be("Concrete")
    replaceCat("CONC-TURF-G") must be("Concrete")
    replaceCat("ALUMINUM") must be("Aluminium")
    replaceCat("ASPH-CONC-F") must be("Asphalt")
    replaceCat("ASPH-TURF-E") must be("Asphalt")
    replaceCat("ASPH-TRTD-G") must be("Asphalt")
    replaceCat("DIRT-TURF-F") must be("Dirt")
    replaceCat("TREATED-G") must be("Treated")
    replaceCat("COP") must be("Composite")
    replaceCat("METAL") must be("Metal")
    replaceCat("Water") must be("Water")
    replaceCat("Grass") must be("Grass")
    replaceCat("STEEL") must be("Metal")
    replaceCat("TRTD-DIRT-P") must be("Dirt")
    replaceCat("TREATED-E") must be("Treated")
    replaceCat("ASPH-CONC-P") must be("Asphalt")
    replaceCat("ICE") must be("Ice")
    replaceCat("Grassed brown clay") must be("Grass")
    replaceCat("Grassed red silt clay") must be("Grass")
    replaceCat("Grassed brown silt clay") must be("Grass")
    replaceCat("Coral grass") must be("Coral")
    replaceCat("Coral") must be("Coral")
    replaceCat("Crushed coral") must be("Coral")
    replaceCat("Gravel dirt") must be("Gravel")
    replaceCat("Coral sand") must be("Sand")
    replaceCat("Sand grass") must be("Sand")
    replaceCat("Sand/grass") must be("Sand")
    replaceCat("Graded earth") must be("Graded soil")
    replaceCat("Limestone/Grass") must be("Stone")
    replaceCat("Soil and Grass") must be("Graded soil")
    replaceCat("Brown silt clay") must be("Silt")
    replaceCat("DIRT-GRVL-P") must be("Gravel")
    replaceCat("GRVL-TURF-P") must be("Gravel")
    replaceCat("GRS") must be("Grass")
    replaceCat("Grassed red clay") must be("Grass")
    replaceCat("MET") must be("Metal")
    replaceCat("Concrete") must be("Concrete")
    replaceCat("Grassed grey silt clay") must be("Grass")
    replaceCat("Grassed yellow clay") must be("Grass")
    replaceCat("Grassed grey gravel") must be("Gravel")
    replaceCat("Brown clay gravel") must be("Gravel")
    replaceCat("Grey gravel") must be("Gravel")
    replaceCat("Grassed white coronas") must be("Grass")
    replaceCat("Grassed black clay") must be("Grass")
    replaceCat("Sandy gravel with clay") must be("Gravel")
    replaceCat("Grey clay") must be("Clay")
    replaceCat("Grassed grey sand") must be("Grass")
    replaceCat("Brown clay") must be("Clay")
    replaceCat("Hard loam") must be("Graded soil")
    replaceCat("Grassed black sand") must be("Grass")
    replaceCat("Red silt clay") must be("Silt")
    replaceCat("Grassed brown clay gravel") must be("Gravel")
    replaceCat("Grassed black silt clay") must be("Grass")
    replaceCat("Grassed black silt") must be("Grass")
    replaceCat("Grassed red silt sand") must be("Grass")
    replaceCat("Grassed limestone gravel") must be("Gravel")
    replaceCat("Grassed red silty clay") must be("Grass")
    replaceCat("Grassed black clay sand") must be("Grass")
    replaceCat("Grassed clay silt clay") must be("Grass")
    replaceCat("Grassed brown silty clay") must be("Grass")
    replaceCat("Grassed river gravel") must be("Gravel")
    replaceCat("Red clay") must be("Clay")
    replaceCat("Grassed black clay silt") must be("Grass")
    replaceCat("Grass red silty clay") must be("Grass")
    replaceCat("Grassed Red Clay") must be("Grass")
    replaceCat("Grassed clay") must be("Grass")
    replaceCat("Grassed grey silt sand") must be("Grass")
    replaceCat("Grassed Sand") must be("Grass")
    replaceCat("Grassed silt clay") must be("Grass")
    replaceCat("White gravel") must be("Gravel")
    replaceCat("Grey silt clay") must be("Silt")
    replaceCat("Grassed grey clay") must be("Grass")
    replaceCat("Grassed white gravel") must be("Gravel")
    replaceCat("Red gravel") must be("Gravel")
    replaceCat("GVL") must be("Gravel")
    replaceCat("Grassed brown gravel") must be("Gravel")
    replaceCat("Grassed Brown Clay") must be("Grass")
    replaceCat("Grassed yellow gravel") must be("Gravel")
    replaceCat("BIT") must be("Bitume")
    replaceCat("Grassed yellow silt clay") must be("Grass")
    replaceCat("grass coral") must be("Grass")
    replaceCat("Yellow gravel") must be("Gravel")
    replaceCat("Gravel") must be("Gravel")
    replaceCat("Stone Dust") must be("Stone")
    replaceCat("turf") must be("Grass")
    replaceCat("Turf") must be("Grass")
    replaceCat("asphalt/gravel") must be("Asphalt")
    replaceCat("Ice") must be("Ice")
    replaceCat("grass") must be("Grass")
    replaceCat("ASPHALT") must be("Asphalt")
    replaceCat("gravel") must be("Gravel")
    replaceCat("paved") must be("Paved")
    replaceCat("TURF/CHIPSEAL") must be("Grass")
    replaceCat("GRAVEL/TURF") must be("Gravel")
    replaceCat("SAND/GRAVEL/AS") must be("Gravel")
    replaceCat("TREATED GRAVEL") must be("Gravel")
    replaceCat("TURF/GRAVEL/AS") must be("Gravel")
    replaceCat("COM") must be("Composite")
    replaceCat("Gravel/Asphalt mix") must be("Asphalt")
    replaceCat("SAND/GRAVEL") must be("Gravel")
    replaceCat("LOOSE GRAVEL") must be("Gravel")
    replaceCat("SAN") must be("Sand")
    replaceCat("Turf / Gravel") must be("Gravel")
    replaceCat("CLAY") must be("Clay")
    replaceCat("Gravel/Snow") must be("Gravel")
    replaceCat("OILED") must be("Oil")
    replaceCat("Turf / Snow") must be("Grass")
    replaceCat("TURF/OIL PACKE") must be("Grass")
    replaceCat("Asphalt") must be("Asphalt")
    replaceCat("OILED GRAVEL/T") must be("Gravel")
    replaceCat("TURF/SOIL") must be("Grass")
    replaceCat("OILED GRAVEL") must be("Gravel")
    replaceCat("Grassed gravel") must be("Gravel")
    replaceCat("TURF/GRAVEL") must be("Gravel")
    replaceCat("GRAVEL/CLAY") must be("Gravel")
    replaceCat("GRAVEL/SAND") must be("Gravel")
    replaceCat("EARTH/TURF") must be("Graded soil")
    replaceCat("SAND/CLAY/GRAV") must be("Gravel")
    replaceCat("CLAY/GRAVEL/TU") must be("Gravel")
    replaceCat("CLAY/GRAVEL") must be("Gravel")
    replaceCat("TURF/ASPHALT") must be("Asphalt")
    replaceCat("CLAY/SAND") must be("Clay")
    replaceCat("TURF/SNOW") must be("Grass")
    replaceCat("ASPHALT/TURF") must be("Asphalt")
    replaceCat("GRAVEL/CLAY/SA") must be("Gravel")
    replaceCat("PACKED GRAVEL") must be("Gravel")
    replaceCat("CRUSHED ROCK") must be("Rock")
    replaceCat("TURF/CLAY") must be("Grass")
    replaceCat("TURF/GRAVEL/CL") must be("Gravel")
    replaceCat("TURF/EARTH/GRA") must be("Grass")
    replaceCat("CONC/GRVL") must be("Gravel")
    replaceCat("TURF/GRAVEL/SN") must be("Gravel")
    replaceCat("TREATED SAND") must be("Sand")
    replaceCat("TURF/EARTH") must be("Grass")
    replaceCat("EARTH") must be("Graded soil")
    replaceCat("TURF/GRVL") must be("Gravel")
    replaceCat("GRAVEL/SAND/CL") must be("Gravel")
    replaceCat("TURF/TREATED G") must be("Grass")
    replaceCat("OILED DIRT") must be("Dirt")
    replaceCat("CLAY/TURF") must be("Clay")
    replaceCat("TURF/ASP") must be("Asphalt")
    replaceCat("ASP/TURF") must be("Asphalt")
    replaceCat("OLD ASP") must be("Asphalt")
    replaceCat("GRVL/CLAY") must be("Gravel")
    replaceCat("SAND/GRVL") must be("Gravel")
    replaceCat("DIRT-SAND") must be("Sand")
    replaceCat("water") must be("Water")
    replaceCat("GRVL/ASP") must be("Asphalt")
    replaceCat("GRVL/TURF") must be("Gravel")
    replaceCat("CLAY/GRVL") must be("Gravel")
    replaceCat("SNOW") must be("Snow")
    replaceCat("Sand") must be("Sand")
    replaceCat("GRASS&amp;GRAVEL") must be("Gravel")
    replaceCat("TRTD GRVL") must be("Gravel")
    replaceCat("GRAVEL/GRASS") must be("Gravel")
    replaceCat("GRASS/GRAVEL") must be("Gravel")
    replaceCat("STEEL-CONC") must be("Concrete")
    replaceCat("EARTH/SNOW") must be("Graded soil")
    replaceCat("SOFT SAND") must be("Sand")
    replaceCat("Turf/Snow") must be("Grass")
    replaceCat("GRASS/SNOW") must be("Grass")
    replaceCat("GRVL-DIRT-G") must be("Gravel")
    replaceCat("PEM") must be("Macadam")
    replaceCat("Asphalt/Turf") must be("Asphalt")
    replaceCat("CONC-TURF-F") must be("Concrete")
    replaceCat("ASPH-GRVL-G") must be("Asphalt")
    replaceCat("LAT") must be("Laterite")
    replaceCat("UNK") must be("Unknown")
    replaceCat("gras") must be("Grass")
    replaceCat("U") must be("Unknown")
    replaceCat("Paved") must be("Paved")
    replaceCat("concrete") must be("Concrete")
    replaceCat("ASPH/GRVL") must be("Asphalt")
    replaceCat("ASPH/GRASS") must be("Asphalt")
    replaceCat("sand/grass") must be("Sand")
    replaceCat("Oilgravel") must be("Gravel")
    replaceCat("GRVL/GRASS") must be("Gravel")
    replaceCat("Oligravel/GRVL") must be("Gravel")
    replaceCat("Oilgravel/sand") must be("Gravel")
    replaceCat("Tarmac") must be("Tarmac")
    replaceCat("Graded Hardcore") must be("Graded soil")
    replaceCat("Grass/Graded Hardcore") must be("Grass")
    replaceCat("Concrete/Asphalt") must be("Asphalt")
    replaceCat("Grass/Asphalt") must be("Asphalt")
    replaceCat("Grass/Asphalt Insert 1968X59 Feet") must be("Asphalt")
    replaceCat("Concrete/Grass") must be("Concrete")
    replaceCat("Bituminous") must be("Bitume")
    replaceCat("GRASS/HARDCORE") must be("Grass")
    replaceCat("Gravel/Grass") must be("Gravel")
    replaceCat("GRASS OR EARTH NOT GRADED OR ROLLED") must be("Grass")
    replaceCat("Tar - lights 5 clicks on 124.8") must be("Tarmac")
    replaceCat("Tar") must be("Tarmac")
    replaceCat("tar") must be("Tarmac")
    replaceCat("BRI") must be("Brick")
    replaceCat("MAC") must be("Macadam")
    replaceCat("'asphalt'") must be("Asphalt")
    replaceCat("graded earth") must be("Graded soil")
    replaceCat("Hard") must be("Graded soil")
    replaceCat("CONC-TRTD") must be("Concrete")
    replaceCat("Grass/gravel") must be("Gravel")
    replaceCat("Grass Dirt") must be("Grass")
    replaceCat("Clay/grass") must be("Clay")
    replaceCat("Gravel/grass") must be("Gravel")
    replaceCat("Rock/Gravel/Clay") must be("Gravel")
    replaceCat("Hard mud") must be("Graded soil")
    replaceCat("Grass/Clay") must be("Grass")
    replaceCat("Grass/rolled earth") must be("Grass")
    replaceCat("Hard clay") must be("Clay")
    replaceCat("Grass over hard gravel") must be("Gravel")
    replaceCat("Rocky gravel") must be("Gravel")
    replaceCat("Sod with gravel & sand") must be("Gravel")
    replaceCat("Grass/red clay") must be("Grass")
    replaceCat("Grass/sandy soil") must be("Grass")
    replaceCat("Sod over hard clay") must be("Clay")
    replaceCat("Dirt/grass") must be("Dirt")
    replaceCat("Sand/clay") must be("Clay")
    replaceCat("Grass/dirt") must be("Grass")
    replaceCat("Gravel/soil") must be("Gravel")
    replaceCat("Grass/clay") must be("Grass")
    replaceCat("Grass/Moss") must be("Grass")
    replaceCat("Grass over rock") must be("Grass")
    replaceCat("Gravel/dirt") must be("Gravel")
    replaceCat("Asphalt/Concrete") must be("Asphalt")
    replaceCat("Clay") must be("Clay")
    replaceCat("Grass over gravel") must be("Gravel")
    replaceCat("Dirt/rock") must be("Dirt")
    replaceCat("Asphalt concrete") must be("Asphalt")
    replaceCat("Sand laterite") must be("Sand")
    replaceCat("GRVL-TURF-G") must be("Gravel")
    replaceCat("UNKNOWN") must be("Unknown")
    replaceCat("grass/concrete") must be("Grass")
    replaceCat("Dirt") must be("Dirt")
    replaceCat("Bitumen") must be("Bitume")
    replaceCat("ground") must be("Ground")
    replaceCat("ASPH-TRTD-F") must be("Asphalt")
    replaceCat("Brown gravel") must be("Gravel")
    replaceCat("PER") must be("Permanent")
    replaceCat("CONC-TRTD-G") must be("Concrete")
    replaceCat("Grassed red silt") must be("Grass")
    replaceCat("Grassed red clay gravel") must be("Gravel")
    replaceCat("ASPH-DIRT-P") must be("Asphalt")
    replaceCat("PIERCED STEEL PLANKING / LANDING MATS / MEMBRANES") must be("Metal")
    replaceCat("ASPH/ CONC") must be("Asphalt")
    replaceCat("CONCRETE") must be("Concrete")
    replaceCat("Unknown") must be("Unknown")
    replaceCat("grass - herbe  (planeur)") must be("Grass")
    replaceCat("grass - herbe  (avion)") must be("Grass")
    replaceCat("Unpaved") must be("Unpaved")
    replaceCat("Grass - Herbe -> Avion - ULM") must be("Grass")
    replaceCat("Grass - Herbe") must be("Grass")
    replaceCat("UnPaved") must be("Unpaved")
    replaceCat("UNPAVED") must be("Unpaved")
    replaceCat("BITUMINOUS") must be("Bitume")
    replaceCat("asph") must be("Asphalt")
    replaceCat("CAUTION: ATC do NOT apply wake turbulence separation ! GRS.") must be("Grass")
    replaceCat("ASP/CONC") must be("Asphalt")
    replaceCat("GRAVEL / CINDERS / CRUSHED ROCK / CORAL/SHELLS / SLAG") must be("Gravel")
    replaceCat("GRVL-GRASS") must be("Gravel")
    replaceCat("ASPHALTH") must be("Asphalt")
    replaceCat("Soil") must be("Graded soil")
    replaceCat("packed dirt") must be("Dirt")
    replaceCat("COR") must be("Coral")
    replaceCat("DIRT-GRVL-G") must be("Gravel")
    replaceCat("Gravel/clay") must be("Gravel")
    replaceCat("Natural Soil") must be("Graded soil")
    replaceCat("Ice - frozen lake") must be("Ice")
    replaceCat("Volcanic ash impregnated with bitumen") must be("Bitume")
    replaceCat("Volcanic ash/soil") must be("Graded soil")
    replaceCat("Grass on coral") must be("Grass")
    replaceCat("Paved/Compacted schist") must be("Paved")
    replaceCat("Paved/Gravel") must be("Gravel")
    replaceCat("CLA") must be("Clay")
    replaceCat("Sealed") must be("Sealed")
    replaceCat("SNO") must be("Snow")
    replaceCat("bitumen/gravel") must be("Gravel")
    replaceCat("GRV") must be("Gravel")
    replaceCat("CONCRETE AND ASP") must be("Asphalt")
    replaceCat("NEOPRENE") must be("Neoprene")
    replaceCat("Conc") must be("Concrete")
    replaceCat("TRTD-DIRT-F") must be("Dirt")
    replaceCat("Brown Silt clay") must be("Silt")
    replaceCat("Asphaltic Concrete") must be("Asphalt")
    replaceCat("DIRT-E") must be("Dirt")
    replaceCat("GRVL-DIRT-E") must be("Gravel")
    replaceCat("Grassed blackclay") must be("Grass")
    replaceCat("Grassed white lime stone") must be("Grass")
    replaceCat("Grassed brown sandy clay") must be("Grass")
    replaceCat("Black silt") must be("Silt")
    replaceCat("Grassed black soil") must be("Grass")
    replaceCat("Black clay") must be("Clay")
    replaceCat("Grassed sandy loam") must be("Grass")
    replaceCat("Red clay gravel") must be("Gravel")
    replaceCat("Grassed brown silt loam") must be("Grass")
    replaceCat("CORAL") must be("Coral")
    replaceCat("Brick") must be("Brick")
    replaceCat("GRAV") must be("Gravel")
    replaceCat("grav") must be("Gravel")
    replaceCat("ASP/CON") must be("Asphalt")
    replaceCat("'concrete'") must be("Concrete")
    replaceCat("Ground") must be("Ground")
    replaceCat("SAND-F") must be("Sand")
    replaceCat("CON/ASP") must be("Asphalt")
    replaceCat("CON/PAD") must be("Concrete")
    replaceCat("GRV/GRASS") must be("Gravel")
    replaceCat("PAD") must be("Pad")
    replaceCat("GRV/PAD") must be("Gravel")
    replaceCat("GRV/MAICILLO") must be("Gravel")
    replaceCat("SAND/GRASS") must be("Sand")
    replaceCat("PAD/GRASS") must be("Pad")
    replaceCat("PAD/CON") must be("Concrete")
    replaceCat("GRAIN") must be("Grain")
    replaceCat("GRV/ASP") must be("Asphalt")
    replaceCat("GRASS/PAD") must be("Grass")
    replaceCat("CON/GRS") must be("Grass")
    replaceCat("CON/MET") must be("Concrete")
    replaceCat("ASP/GRS") must be("Asphalt")
    replaceCat("MET/CON") must be("Concrete")
    replaceCat("Pavement") must be("Paved")
    replaceCat("Paviment hard") must be("Paved")
    replaceCat("Grassed sand clay") must be("Grass")
    replaceCat("CONC/MTAL") must be("Concrete")
    replaceCat("GRVL/PIÇ") must be("Gravel")
    replaceCat("MTAL") must be("Metal")
    replaceCat("conc") must be("Concrete")
    replaceCat("ASP/GRE") must be("Asphalt")
    replaceCat("GRE/GRS") must be("Grass")
    replaceCat("NATURAL SOIL") must be("Graded soil")
    replaceCat("TURF-TRTD-G") must be("Grass")
    replaceCat("Grassed brown loam") must be("Grass")
    replaceCat("ASPH/CONC") must be("Asphalt")
    replaceCat("PAVED") must be("Paved")
    replaceCat("Compacted sand") must be("Sand")
    replaceCat("Compacted coral and sand") must be("Sand")
    replaceCat("Coral penetration") must be("Coral")
    replaceCat("ASPH/GRVL-F") must be("Asphalt")
    replaceCat("Asphalt/Grass") must be("Asphalt")
    replaceCat("Grassed black silt sand") must be("Grass")
    replaceCat("sealed") must be("Sealed")
    replaceCat("unsealed") must be("Unsealed")
    replaceCat("Grass and granite sand") must be("Grass")
    replaceCat("Earth/sand") must be("Sand")
    replaceCat("tar old") must be("Tarmac")
    replaceCat("Grass/Concrete") must be("Grass")
  }

  "Strings with unknown value" should "be marked in red" in {
    replaceCat("PSP") must be("PSP".red)
    replaceCat("C") must be("C".red)
    replaceCat("NSTD") must be("NSTD".red)
    replaceCat("PFC") must be("PFC".red)
    replaceCat("ASB") must be("ASB".red)
    replaceCat("CLOSED") must be("CLOSED".red)
    replaceCat("TER") must be("TER".red)
    replaceCat("None") must be("None".red)
    replaceCat("PIÇ") must be("PIÇ".red)
    replaceCat("PIC") must be("PIC".red)
    replaceCat("ARG") must be("ARG".red)
    replaceCat("SAI") must be("SAI".red)
    replaceCat("B") must be("B".red)
  }
